fix

diff --git a/src/bin/main.sh.in b/src/bin/main.sh.in
--- a/src/bin/main.sh.in
+++ b/src/bin/main.sh.in
@@ -12,7 +12,7 @@ cmd="${1:-}"
 shift || :
 
 usage() {
-  echo "Usage: $0 enroll <part-uuid>" >&2
+  echo "Usage: $0 enroll <part-uuid>|current" >&2
   echo "Usage: $0 unenroll <part-uuid>" >&2
   echo "Usage: $0 status" >&2
 }
@@ -25,6 +25,12 @@ enroll)
   fi
 
   partuuid="$1"
+  if [ "$partuuid" = current ]; then
+    if ! partuuid=$(efibootmgr_get_current_boot_dev_partuuid); then
+      echo "Error: failed to determine current boot partuuid" >&2
+      exit 1
+    fi
+  fi
 
   readarray -t user_efi_partitions < <(get_configured_efi_partitions)
   if [[ "${user_efi_partitions[*]}" == *"$partuuid"* ]]; then
